# This rule is not used by the project fusioninfer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to fusioninfer.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fusioninfer
    app.kubernetes.io/managed-by: kustomize
  name: inferenceservice-viewer-role
rules:
- apiGroups:
  - fusioninfer.io
  resources:
  - inferenceservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fusioninfer.io
  resources:
  - inferenceservices/status
  verbs:
  - get
