apiVersion: fusioninfer.io/v1alpha1
kind: ModelLoader
metadata:
  labels:
    app.kubernetes.io/name: fusioninfer
    app.kubernetes.io/managed-by: kustomize
  name: modelloader-sample
spec:
  # TODO(user): Add fields here
